### ISSUE TITLE
Maximum in given data

### ISSUE THREAD

**Issue by husain2088** [wncc/Hello-Foss-PyThread.cpp#4]
https://github.com/wncc/Hello-Foss-PyThread.cpp/blob/Advanced/src/max.cpp
MPI_Wtime provides incorrect value of time elapsed for given code snippet.

**Comment by AdityaK1729** [comment]
Hi
Allot me for this issue please

**Comment by AdityaK1729** [comment]
Hi I have made a PR, please check

**Comment by LoPA607** [comment]
okay will check soon and respond
